name: 将镜像复制到DockerHub

permissions: write-all        

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: '要拉取的源仓库镜像名称'
        required: true
        default: 'nginx'
      tag:
        description: '镜像标签（默认：latest）'
        required: false
        default: 'latest'
      dockerhub_image:
        description: '推送到DockerHub的镜像名称'
        required: true
        default: 'myimage'

env:
  DOCKERHUB_REGISTRY: docker.io

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: 登录到DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: 从源仓库拉取镜像
        run: |
          docker pull ${{ inputs.source_image }}:${{ inputs.tag }}

      - name: 设置Docker镜像的标记名为小写
        run: echo "IMAGE_NAME_LOWER=$(echo '${{ inputs.dockerhub_image }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: 为DockerHub标记镜像
        run: |
          docker tag ${{ inputs.source_image }}:${{ inputs.tag }} ${{ env.DOCKERHUB_REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ inputs.tag }}
      
      - name: 将镜像推送到DockerHub
        run: |
          docker push ${{ env.DOCKERHUB_REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ inputs.tag }}
